### ISSUE TITLE
lengthAsTime does not work.

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#101]
I created a new program, ```swiML/bookExamples/patterns/hand-crossing/hand-crossing-program-intro.xml```, and it cannot be converted to HTML.

```
The required item type of the value of variable $instLengths is element(), but the supplied expression {text {"0"}} has item type text()
```

It only contains one instruction in which the length is expressed as lengthAsTime. I suspect that your layout calculations might not be able to handle non integer values. This might connect to the Roman numeral issue. We might have to find a more general solution.

```
    <instruction>
        <length>
            <lengthAsTime>PT5M33S</lengthAsTime>
        </length>
        <stroke>
            <standardStroke>any</standardStroke>
        </stroke>
        <intensity>
            <startIntensity>
                <zone>easy</zone>
            </startIntensity>
        </intensity>
    </instruction>
```

**Comment by bartneck** [comment]
I am not sure to which issue I should associate this error message. It seems to show for many Jasi Masters program now:

```
An empty sequence is not allowed as the first argument of myData:showLength()
```

**Comment by calloc262** [comment]
should be a fix for this in the latest version

**Comment by bartneck** [comment]
Tested and okay.
