### ISSUE TITLE
continue does not respect laps

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#102]
When laps is defined as the unit of length measure, then the repetition should report the overall length as laps. Right now it converts it to meters.

```
bookExamples/patterns/handshake/handshake-program.html
```

It should show the total number of laps in the continue element.

<img width="549" alt="SCR-20240422-obxx" src="https://github.com/bartneck/swiML/assets/19443755/10a13cd8-828c-4009-ae79-87c341cf9d8a">

**Comment by calloc262** [comment]
should be a fix for this in the latest version

**Comment by bartneck** [comment]
The fix does not seem to work. Could you please try it out with the ```bookExamples/patterns/handshake/handshake-program.xml``` program?

**Comment by bartneck** [comment]
This issue does relate to issue "lengthUnits can be set to lapse #104". The definition of ```<lengthUnit>``` has to be clarified. Originally, it was meant as a default for the instructions. The total length of the program would then also be shown in this unit.

But it was also used to define the poolLength. The pool length cannot be laps and hence we decided to remove this option. We also changed the the way how length is defined in the instructions. We now have explicit distance, laps and time. Hence we no longer need a "default" unit of measure. Or at least we need to define better what consequences it might have. 

We might need to consider including a new element that is specifically used as the default, such as ```<defaultLength>```. It could be used to set the unit in which the program total is set.

**Comment by bartneck** [comment]
Could you please provide and example of how ```<continueLength>``` is supposed to be used in Python?

I tried ```bookExamples/patterns/handshake/handshake-program.xml``` and I get a validation error:

```Assertion evaluation ('(count(.//sw:instruction/sw:rest) = 0)') for element 'continue' on schema type 'continueType' did not succeed. ```

The XSLT transformation is almost okay. The only main problem remains the calculation of the total length of the program. It should be possible to combine lengthAsDistance and lengthAsLaps in a program.

<img width="457" alt="SCR-20240716-joiv" src="https://github.com/user-attachments/assets/99bbdff3-f9ae-4f36-9cda-29e6ca85072a">

**Comment by calloc262** [comment]
Here is an example of a continue in python:
oneSet3=swiML.Continue(
    continueLength=('lengthAsDistance',400),
    instructions=[
        swiML.Instruction(
            length=('lengthAsDistance',100),
            stroke=('drill',('any','any'))
        ),
        swiML.Instruction(
            length=('lengthAsDistance',100),
            stroke=('standardStroke','any'),
            equipment=('pullBuoy')
        )
    ]
)

**Comment by calloc262** [comment]
The rest assertion is failing because you can't have a rest in the middle of a continue as it is meant to be swum continuously.

**Comment by bartneck** [comment]
Thank you for pointing out the error with the rest. But the calculation of the total program length remains an issue.

**Comment by calloc262** [comment]
Yes, I will look into this tomorrow.
I fixed an issue when combining distance and laps the total length was wrong last night but I must've not tested thoroughly enough.

**Comment by bartneck** [comment]
The last outstanding problem with this issue is identical to issue #108. I will close this issue for now.
