### ISSUE TITLE
programLength is not used and should be removed

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#105]
The ```<programLength>``` element is not referenced anymore in the XSD or XSLT file. It should be removed. The length of the program is calculated automatically. The python code has to be adjusted.

**Comment by calloc262** [comment]
Is there still a python file where the programLength exists?
I think it got removed already, as its not in the top level swiML.py file.

**Comment by bartneck** [comment]
It is great if it is already removed from Python. I now removed it from the XSD file. I hope that this does not brake anything.

**Comment by bartneck** [comment]
The ```<programLength>``` is longer present in the python and XSD file.
