### ISSUE TITLE
Right alignment not working

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#107]
The right alignment does no longer work. I created a test file: ```swiML/tests/alignmentTest/timeDistance01.xml```. It shows three levels of alignment of the distance. It was supposed to be right aligned and it was like this in the past.
<img width="434" alt="SCR-20240511-jkvs" src="https://github.com/bartneck/swiML/assets/19443755/c436d5d8-25e8-418d-ba5a-934d5acb3d78">

**Comment by calloc262** [comment]
added fix in latest version

**Comment by bartneck** [comment]
tested and okay.
