### ISSUE TITLE
program length calculation is incorrect

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#108]
I created a program ```/bookExamples/patterns/handshake/handshake-program.html```. It uses a mixture of lengthAsLaps and lengthAsDistance. The total is reported as 520. It is calculated at 200+120+200. There are indeed 120 laps being swum in the main set. The calculation is not respecting the unit of measurement. 120 laps in a 25 meters pool is 3000 meters. The total should be 3400 meters.

It seem that the calculation is treating the number of laps as meters.

<img width="485" alt="SCR-20240514-npop" src="https://github.com/bartneck/swiML/assets/19443755/266c4911-fabd-40ed-a91e-cca8c7a608e0">

**Comment by calloc262** [comment]
added fix to main 
program length is also now output is either meters or laps as defined by lengthUnit.
Still working on an output for total time.

**Comment by bartneck** [comment]
I created a ```handshake-program-manual.xml``` for testing. I get a validation error:
```Assertion evaluation ('(count(.//sw:instruction/sw:rest) = 0)') for element 'continue' on schema type 'continueType' did not succeed. ```
The total program length is also incorrect:
<img width="455" alt="SCR-20240716-kfng" src="https://github.com/user-attachments/assets/d9e55dfc-53ca-407b-b1fa-f44595ed848c">

**Comment by bartneck** [comment]
Decision: always display meters and laps. Both correspond to each other. If a lengthAsTime is present, display it as + xxx minutes. If only time is present then remove meters and laps.

**Comment by bartneck** [comment]
The program length of this program is now 3520 meters / 140.8 Laps. It should be 3400 meters 136 laps

**Comment by calloc262** [comment]
I haven't been able to recreate this bug. 
Both the handshake and the manual xml files compile properly and give the correct program length output.
What file were you using?

**Comment by bartneck** [comment]
This is an interesting one. The program that does not work is called ```handshake-program-test.xml``` in the handshake folder. It is generated through ```handshake-program.py```. The same program created manually ```handshake-program.xml``` does not show the miscalculation.

**Comment by calloc262** [comment]
Bug was caused by python outputting continue Length in XML only as lengthAsDistance. Fix should be in main swiML.py, however could you please check if its working for you as I'm currently getting this bug when trying to run the write function in python:
OSError: [Errno 9] Bad file descriptor 
Still unsure how to fix this, but working on it.

**Comment by bartneck** [comment]
I updated the ```handshake-program.py``` and it worked fine. The XML is now valid and the program length is accurate.
