### ISSUE TITLE
XML first line missing

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#109]
When creating a program with Python, the first line necessary for all documents is missing:
```
<?xml version="1.0" encoding="UTF-8"?>
```
I tried to create a new program with 

```bookExamples/patterns/handshake/handshake-program.py```

**Comment by bartneck** [comment]
I manually added the line of code to the ```handshake-program.xml``` file.

**Comment by calloc262** [comment]
added fix to main swiML.py file

**Comment by bartneck** [comment]
tested and okay
