### ISSUE TITLE
Default python version

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#110]
When the ```<swiMLVersion>``` element is not set, swiML.py sets it to 1.1 by default. It should instead be the latest version in the root directory.

**Comment by calloc262** [comment]
Added fix to main 
default is now the latest version in root directory.
Long term this may need to change as it probably should be the latest full release in the versions folder

**Comment by bartneck** [comment]
I added a folder "latest" to the version folder. We can add the latest stable version to this folder. We can then change the default behavior to this folder. We still need to iron out a few issues before declaring it stable and to move the current files. We should also consider moving the swiML.py into that folder.

**Comment by bartneck** [comment]
This has not yet been achieved with the latest bug fixes.

**Comment by calloc262** [comment]
Pushed fix to main 
Although there is still nothing in the latest folder, 
I assume this will be the final copy of 2.1/2.2 when it's done.

**Comment by bartneck** [comment]
Yes, this should be the goal of this round of revisions. 

Tested and works as requested. 
How can I instruct python to point to the root directory if I want to?

**Comment by calloc262** [comment]
This currently isn't possible but I could change it so if the version specified is 'root' or 'main' it will point at the root directory, as this is what 'latest' was doing previously.

**Comment by bartneck** [comment]
Yes, please set it to ```main```

**Comment by bartneck** [comment]
tested and okay.
