### ISSUE TITLE
Alignment not working

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#111]
I created the ```bookExamples/swiML-documentation/alignment.xml``` file to test the ```<excluderAlignment>``` element. While testing, I discovered that even with two simple repetitions, the alignment fails when there is too much difference between them.

When only the stroke is different, it works:

<img width="438" alt="SCR-20240524-karr" src="https://github.com/bartneck/swiML/assets/19443755/05cc55a9-f874-4dcb-8aaf-9951671d6e36">

When ```<rest>``` is added, it fails.
<img width="428" alt="SCR-20240524-kayw" src="https://github.com/bartneck/swiML/assets/19443755/5a4a9cef-e4cf-4ea1-9a0c-f94482a80ad9">

Is there an automatic check that stops the alignment when the difference is too large? If so, what exactly is the threshold?

**Comment by bartneck** [comment]
Setting the ```<excludeAlign>``` does not seem to have any effect either.

**Comment by bartneck** [comment]
I am not sure if this is the same error, but the repetitions in the first set in this file do not align:

```jasiMasters/JasiMasters2024032601.xml```


<img width="441" alt="SCR-20240524-npzy" src="https://github.com/bartneck/swiML/assets/19443755/b249536e-dcd2-4471-b542-8a225c787c67">

**Comment by calloc262** [comment]
There is currently a check that means any instruction of the same type will not align if a certain number of characters apart,
This is set to 9 so any 10 characters apart will not align
So I think this is still acting as intended:
In the first case, the repetitions are exactly 10 characters apart so just missing that alignment.
In the second case, the 1st, 3rd and 4th are aligned on the left of the **50** the 2nd repetition is over 9 characters longer so does not align with the rest.

This should probably be discussed again on Friday so we can choose a definitive option to move forward with.

**Comment by bartneck** [comment]
Thank you for clarifying the alignment threshold. In the second example, should line 8,10,12 and 20 not align at the "x"? Why is line 20 so much intended?

**Comment by bartneck** [comment]
The existence of the ```<excludeAlign>``` element needs to be discussed. There seems very little reason to use it anymore. Unless we force elements to align by setting it to false.

**Comment by bartneck** [comment]
Decision: add alignProgram as meta element on top, check if all excludeAligns could be the same. No more specific excludeAlignContinue. 
Keep a threshold of 10 for the default automatic system that can be manually overridden in both directions.

**Comment by bartneck** [comment]
The overall alignProgram works. But there is still a problem with the individual alignments. I edited the ```bookExamples/swiML-documentation/alignment.xml``` file. There are three ```<instruction>`` elements and the first one is set to NOT align. It still does.

<img width="440" alt="SCR-20240716-kosc" src="https://github.com/user-attachments/assets/c8cd2405-8b73-4d8e-8d6a-e701cc7a4e2d">

**Comment by calloc262** [comment]
Based on the most recent push I think you have the booleans confused:
excludeAlignRepetition should be set to **true** if you don't want it to align, in the file alignment.xml you have done the opposite, which looks like its working correctly in this image

**Comment by bartneck** [comment]
Two instructions are set to true and one is set to false. The first one is set to false. So it should indeed try to align. But the other two are set to true. So there should be nothing to align to. The question arises what happens in case of conflicts. Can you please specify what the policy is?

I uploaded another example. Three elements. excludeAlign set to false false true. Still, the last instruction does get aligned.

**Comment by bartneck** [comment]
tested and okay
