### ISSUE TITLE
simplify does not work with nested repetition

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#121]
In the file ```JasiMasters2024041401-edit02.xml``` there is a simplified repetition. Both nested instructions are 100 meters. So simplify should work. It has to be 2 x 100 as [ The first embedded instruction then needs to be 4x25. The second could be shown simply as 1.

<img width="547" alt="SCR-20240716-lvnw" src="https://github.com/user-attachments/assets/92b48317-f82c-4a8d-bb36-1e97cea41a2f">

**Comment by calloc262** [comment]
This is the same confusion as earlier, 4x25 is not swum as 100 meters. 
Simplify only works when all child instructions are the exact same continuously swum distance. 
This problem is if there is still no failed assertion when the XML is validated

**Comment by bartneck** [comment]
Thank you for this clarification. I added this to the documentation and I will add this issue as a feature request.
