### ISSUE TITLE
CSS types

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#60]
Create different CSS files depending on output (A4, 11cm for book, Screen). Have an XML element to set the desired output type.

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by bartneck** [comment]
Hi Mstanic05,
Thank you for your interest in this project. Can you please tell me a bit more about your background/skills/goals? It would be great to have more people working on this project. Feel free to message me directly.

**Comment by bartneck** [comment]
The new <layoutWidth> sets the width of the HTML layout. It is done in characters. 50 characters are 11cm. The HTML file overrides the CSS file to set the width and max-width for all affected classes.
