### ISSUE TITLE
SegmentName

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#7]
The `<segmentName>` element can currently occur within any `<repetition>` or `<instruction>`. This makes no sense. It should only be allowed at the top level, right under the first <instruction> element. In the folder bookExamples, the file segmentName.xml has valid and invalid test cases.

**Comment by calloc262** [comment]
had it working but now the assertion doesn't work again.
it works when testing in the xml file with Xpath builder 
but not when validating against actual xsd file
