### ISSUE TITLE
instruction in repetition invalid

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#71]
The following example give and error in validation. This is visible in jasiMasaters2024012101.xml

    
    <instruction>
        <repetition>
            <repetitionCount>4</repetitionCount>
            <stroke><standardStroke>freestyle</standardStroke></stroke>
            <equipment>fins</equipment>
            <instruction>
                <length>
                    <lengthAsDistance>100</lengthAsDistance>
                </length>
                <stroke>
                    <drill>
                        <drillName>123</drillName>
                        <drillStroke>freestyle</drillStroke>
                    </drill>
                </stroke>
            </instruction>
        </repetition>
    </instruction>
    
    
    <instruction>
        <length>
            <lengthAsDistance>100</lengthAsDistance>
        </length>
        <stroke>
            <drill>
                <drillName>123</drillName>
                <drillStroke>freestyle</drillStroke>
            </drill>
        </stroke>
    </instruction>

**Comment by calloc262** [comment]
This error occurred because the 100 in the repetition has two different strokes defined, which we decided wasn't going to be allowed. It's from the assertion related to this comment you sent in an email the other day 

<!-- to do: cross-check that only one stroke is defined. —>

**Comment by calloc262** [comment]
<!-- to do: cross check that only one stroke is defined. —>

**Comment by calloc262** [comment]
<!-- to do: cross check that only one stroke is defined. —>

**Comment by calloc262** [comment]
<!-- to do: cross check that only one stroke is defined. —>

**Comment by calloc262** [comment]
\
\<!-- to do: cross check that only one stroke is defined. —>

**Comment by bartneck** [comment]
I see your point. I was caught out by thinking that drill is not a stroke.
