### ISSUE TITLE
operation of excludeAlign

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#73]
The functionality of ```<excludeAlign>``` is a bit unclear and needs to be better described in the documentation. In the ```JasiMasters2024012101.xml``` file, there are several alignment issues. Using the element does not seem to help with the line break of the intensity.

<img width="434" alt="SCR-20240202-krao" src="https://github.com/bartneck/swiML/assets/19443755/93e6b526-0dc8-45a3-9374-8d1920ecbb12">

**Comment by bartneck** [comment]
Here is another example of how the allignment might not work exactly as intended. 
<img width="494" alt="SCR-20240212-kvaf" src="https://github.com/bartneck/swiML/assets/19443755/8466c21e-e377-47fc-9530-4ca336290e4e">

**Comment by bartneck** [comment]
I checked ```JasiMasters2024021201.xml``` today and I wonder if the "First set" instructions should be aligned. They are in the same segment. Or does ```<continue>``` and ```<repetition>``` not align with each other. Could you please comment?

<img width="463" alt="SCR-20240227-jhdg" src="https://github.com/bartneck/swiML/assets/19443755/60be0886-6aa5-49b8-9210-541f047e16c5">

**Comment by calloc262** [comment]
currently continue and repetitions don't align, they could but repetitions tend to be a lot longer 
the symbols are also different widths so i think it would cause some misalignment in the text to the left

**Comment by bartneck** [comment]
Okay. I will close this issue.
