### ISSUE TITLE
Simplified repetition bold formatting 

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#74]
When using more than "1" repetition in a simplified repetition, the counter is not bold. Compare the 1 to the 2. This is part of ```JasiMasters2024020401.xml```

<img width="483" alt="SCR-20240206-obpo" src="https://github.com/bartneck/swiML/assets/19443755/276e1750-1151-40b7-aeff-25e7345310fe">

**Comment by calloc262** [comment]
added fix to main
let me know if it's still not working

**Comment by bartneck** [comment]
tested and it works. thanks!
