### ISSUE TITLE
intensity across causes line break

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#75]
When intensity across a repetition is specified, it results in a line break.
<img width="485" alt="SCR-20240206-ofvh" src="https://github.com/bartneck/swiML/assets/19443755/92734c00-d9f6-4234-b6c5-60d77d98052d">

**Comment by bartneck** [comment]
This problem can easily be spotted in a simple example of ```firstExample09Full.xml```
<img width="443" alt="Screenshot 2024-02-09 at 4 04 22 PM" src="https://github.com/bartneck/swiML/assets/19443755/ebae6440-1ce0-47f3-b962-5a6db70a70b9">

**Comment by calloc262** [comment]
added the fix to 2.0 now should be working
will need to discuss line breaking problem next week as it can still occur if the line is long enough

**Comment by bartneck** [comment]
I checked the transformation of ```JasiMasters2024012101.xml``` again today, and there are still some problems. I transformed with version 2.0 and 2.1.
<img width="507" alt="SCR-20240227-jeoz" src="https://github.com/bartneck/swiML/assets/19443755/0420dba1-25fd-477d-a383-7c9130c2d66b">

**Comment by calloc262** [comment]
newest version has updated xslt functions to fit intensities

**Comment by bartneck** [comment]
tested. resolved. well done!
