### ISSUE TITLE
validation error for simplified repetition

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#76]
A validation error occurs when a simplified repetition includes a continue. This might be due to the fact that the ```<instruction>``` inside the ```<continue>``` are not of the same ```<length>``` as required by the ```<simplify>true<simplify>``` element. An example can be found in this file:

```JasiMasters2024021301.xml```

The error message is:

```Assertion evaluation ('                 ((./sw:simplify = true()) and (every $length in .//sw:length                     satisfies $length/*[1] = (.//sw:length)[1]/*[1])) or ./sw:simplify = false() or count(./sw:simplify) = 0') for element 'repetition' on schema type 'repetitionType' did not succeed. ```

**Comment by bartneck** [comment]
When I compile with 2.0 the total length is incorrect. It is not 4000m
<img width="513" alt="SCR-20240226-qmzo" src="https://github.com/bartneck/swiML/assets/19443755/5ef61530-cc26-4995-a307-a4aabe52d7d8">

**Comment by bartneck** [comment]
When I compile with 2.1, the total length is still wrong, but also the lengths are missing.
<img width="475" alt="SCR-20240226-qncr" src="https://github.com/bartneck/swiML/assets/19443755/0e0330de-0548-4420-ac3b-830aff1a222d">

**Comment by bartneck** [comment]
When I try to compile the ```JasiMasters2024025001.py``` file, I get the error:
```
Exception: Cannot simplify continue with repetitions of different lengths
```

**Comment by calloc262** [comment]
just a note for JasiMasters2024022001.html 
4000m is the correct total length as the 3x200 set is denoted as 3 x 3 x 200 as its still a repetition and you would be repeating 3 200s 3 times, if you wanted just the one set then you should leave the repetition count empty or not include it

**Comment by bartneck** [comment]
```<RepetitionCount>``` is a required element for a repetition in the XSD schema. If I set ```<simplify>``` to true I get the correct total distance calculation (2800), but the repetition is shown as 6x100, not 3x200 as it should be. Have a look at the JPEG. It shows what was intended. 3x200 in which each 200 is broken into 2x100 (continue). How can this be modelled?

**Comment by calloc262** [comment]
this issue should be fixed in the python 
not 100% sure about the xsd but it was working when last checked

**Comment by bartneck** [comment]
tested and okay. Great job!
