### ISSUE TITLE
import/export not working

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#89]
I wrote a very simple program to test the import/export function ```import-export-test-01.py```:

```
import swiML
program=swiML.readXML('JasiMasters2024021301.xml')
swiML.writeXML('JasiMasters2024021301-phyton-out.xml',program)
```

I get many errors when running this script. The XML is valid swiML.

**Comment by calloc262** [comment]
Could you check the filename for the write as that file doesn't exist in your testing folder 
python is also misspelled (phyton) so that could also be an issue

**Comment by bartneck** [comment]
The output file does not exist. Python fails to write it. Here is a screenshot of the program and the error.
<img width="1412" alt="Screenshot 2024-02-23 at 12 43 09 PM" src="https://github.com/bartneck/swiML/assets/19443755/80daf0af-ff7e-49d4-9cf2-56236c653e25">

**Comment by bartneck** [comment]
I had added the ```<layoutWidth>``` element and the python code does not yet know about it and the transformation fails.

```
import swiML 
swiML.writeXML('importExportTest/JasiMasters2024032401-rewrite.xml',swiML.readXML('importExportTest/JasiMasters2024032401.xml'))
```

**Comment by bartneck** [comment]
When running the program seen above, it also changes the XML file that was read. It removes all of the meta data. Here is the original XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<program xmlns="https://github.com/bartneck/swiML"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/bartneck/swiML/version/2/2.1 https://raw.githubusercontent.com/bartneck/swiML/main/swiML.xsd">
```
and here it is after it was read.

```
<?xml version="1.0" encoding="UTF-8"?>
<program>
```
This is NOT the file that was written. It also changes the XML file that is read. This should of course not happen.

**Comment by bartneck** [comment]
Any swiML XML file should be able to be read and the wrote out again, producing the exact same result.

**Comment by bartneck** [comment]
checked and okay
