### ISSUE TITLE
equipment missing from continue

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#94]
In the file ```JasiMasters2024031001.py``` I added equipment to the first continue:
```
oneSet=swiML.Continue(
    equipment=('fins','pads'),
    instructions=[oneSet1,oneSet2,oneSet1,oneSet3,oneSet1,oneSet4]
)
```
The resulting XML file does not contain any equipment.

**Comment by calloc262** [comment]
fix added to all 3 swiML.py files
was an issue for all instruction tags in a continue weren't being added 
not just equipment

**Comment by bartneck** [comment]
tested and solved. Well done!
