### ISSUE TITLE
stopIntensity not working in Python

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#95]
When adding a stopIntensity to the code, it does not work. Option 1:
```
intensity=('startIntensity',('zone','easy')),
intensity=('stopIntensity',('zone','max'))
```
Results in an error message: keyword argument repeated: intensity

When writing it in one line, the stopIntensity is ignored:
```
intensity=('startIntensity',('zone','easy'),'stopIntensity',('zone','max'))
```
This can be seen in the file ```JasiMasters2024031001.py```

**Comment by calloc262** [comment]
should be fixed in latest version in all 3 swiML.py files 

Using the second option:
`intensity=('startIntensity',('zone','easy'),'stopIntensity',('zone','max'))`

**Comment by bartneck** [comment]
checked and solved. Thanks.
