### ISSUE TITLE
The lap numbers are not aligned

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#98]
When writing the ```<length>``` as ```<lengthAsLaps>``` then the resulting HTML file has some layout error.

The error is visible in the ```squared-square-program.html```
<img width="448" alt="SCR-20240321-ootm" src="https://github.com/bartneck/swiML/assets/19443755/9b3d494e-3b3d-421d-8ecf-9ea9d6fd9814">

**Comment by bartneck** [comment]
The numbers should be right aligned.

**Comment by calloc262** [comment]
added fix to main

**Comment by bartneck** [comment]
There are some random numbers at the end of the program now.

**Comment by bartneck** [comment]
Here is an example of the random numbers at the bottom. It's probably just some leftover debug code.
<img width="466" alt="SCR-20240325-hrgv" src="https://github.com/bartneck/swiML/assets/19443755/f6215d5d-d444-47e2-b67c-c20b714ad336">

**Comment by calloc262** [comment]
forgot to remove after testing 
should be all good now

**Comment by bartneck** [comment]
tested and works. Great work!
